<a href="https://colab.research.google.com/github/c-bujari/CAP4630/blob/master/HW_1/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework Assignment 1
### CAP 4630 Artificial Intelligience


## Problem 2
If $A$ is a $m \times n$ matrix and $B$ is a $n \times p$ matrix such that

$\begin{equation*}
  A_{m,n} =
    \begin{bmatrix}
      a_{1,1} & a_{1,2} & \dots & a_{1,n} \\
      a_{2,1} & a_{2,2} & \dots & a_{2,n} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{m,1} & a_{m,2} & \dots & a_{m,n}
    \end{bmatrix}
\end{equation*}$ and $\begin{equation*}
  B_{n,p} =
    \begin{bmatrix}
      b_{1,1} & b_{1,2} & \dots & b_{1,p} \\
      b_{2,1} & b_{2,2} & \dots & b_{2,p} \\
      \vdots & \vdots & \ddots & \vdots \\
      b_{n,1} & b_{n,2} & \dots & b_{n,p}
    \end{bmatrix}
\end{equation*}$

the product $C$ = $A \times B$ of these two matrices is the $m \times p$ matrix:

$\begin{equation*}
  C_{m,p} =
    \begin{bmatrix}
      c_{1,1} & c_{1,2} & \dots & c_{1,p} \\
      c_{2,1} & c_{2,2} & \dots & c_{2,p} \\
      \vdots & \vdots & \ddots & \vdots \\
      c_{m,1} & c_{m,2} & \dots & c_{m,p}
    \end{bmatrix}
\end{equation*}$

A pair of matrices which does not follow these guidelines (for example, if $D$ = $m \times n$ and $E$ = $p \times q$, where $n \neq p$) cannot be multiplied. For the purposes of this assignment, such a pair is considered ***incompatible***.

For an entire list of matrices to be multiplied in succession, each subsequent pair must follow this rule. In my implementation, any incompatible matrix in the list will trigger an exception message and terminate the program, citing the problematic matrices.

      


In [0]:
# Import numpy, as we will need it to work with matrices
import numpy as np

In [0]:
# List of matrix arrays:
matrix_list = []

# Add in test matrices
# (This sequence of test matrices should not trigger any exceptions).
## Auto-creating matrices with values 0 - 12, shaping it to the dimensions given
matrix_list.append(np.arange(12).reshape(3,4))
matrix_list.append(np.arange(12).reshape(4,3))
## Explicitely assigning values to the matrix
matrix_list.append(np.array(([[5,98,12,87],[7,2,6,7],[7,5,2,513]])))
## Auto-creating matrices with values 0 - 8, shaping it to the dimensions given
matrix_list.append(np.arange(8).reshape(4,2))
matrix_list.append(np.arange(8).reshape(2,4))

# Uncommenting this test matrix WILL cause an exception (for testing purposes)
# matrix_list.append(np.arange(6).reshape(2,3))

In [0]:
# Evaluates whether the matrices can be multiplied in the first place...
def evaluate_pair(matrix_a, matrix_b):

  # Multiply matrices using built-in numpy.matmul() function
  if matrix_a.shape[1] == matrix_b.shape[0]:
    return np.matmul(matrix_a, matrix_b)

  else:
    raise Exception("\nThe matrices \n" + str(matrix_a) + "\n and \n" + str(matrix_b) + "\n are NOT compatible!")


In [0]:
# Iterates through a given list of matrices.
# Calls evaluate_pair() on every combination (i, i + 1)
def multiply_matrices(list):
  for i in range(len(list) - 1):
    # If we are past the first two matrices in the list, use the last result
    # as one of the matrices being multiplied
    if i > 0: 
      resultant = evaluate_pair(resultant, list[i + 1])
    # Otherwise, get a first result to start off with.
    else:
      resultant = evaluate_pair(list[i], list[i + 1])
  
  # If we have reached this point, we can return the final result of multiplying
  # all matrices in the list.
  return resultant


In [171]:
# Call multiply_matrices on the list created earlier...
print("Evaluating matrices...\n")
result = multiply_matrices(matrix_list)

print("Result of multiplying all matrices in list:\n" + str(result))

Evaluating matrices...

Result of multiplying all matrices in list:
[[  962856  1406286  1849716  2293146]
 [ 2781192  4062502  5343812  6625122]
 [ 4599528  6718718  8837908 10957098]]
